### ISSUE TITLE
Run configuration

### ISSUE THREAD

**Issue by LKAMING97** [snap-research/F8Net#2]
Hello, you are doing a very good job, I would like to know what the configuration to run this code should be like

**Comment by deJQK** [comment]
Thanks for your interest. You could follow the Model Training section in [Getting Started](https://github.com/snap-research/F8Net#getting-started). Depending on the training method (conventional vs. tiny-finetuning) and model (e.g. MobileNet V1/V2 or ResNet18/50) you could use different yml file in the [apps](https://github.com/snap-research/F8Net/tree/main/apps) folder.
